spring.application.name=@project.artifactId@
server.port=${APP_PORT}

spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true

jwt.secret=${JWT_SECRET}
